ログイン機能実装
kenny-kento/tips-memo pull request #2
Opened 2023-01-20 06:01 UTC by kenny-kento

ログイン機能を実装いたしました。

サインイン時入力項目
・名前
・メールアドレス
・パスワード
・パスワード確認用

ログイン項目
・メールアドレス
・パスワード

2023-01-20 06:49 UTC, yupimaru requested changes
コメントしました！

2023-01-20 06:49 UTC, yupimaru commented on backend/app/controllers/application_controller.rb
> +end
L2,4,14の空白行って必要ですか？

2023-01-20 06:49 UTC, yupimaru commented on backend/config/application.rb
> +    config.api_only = false
```ruby
config.api_only = false
```

今回、RailsはAPIとしてのみ動くはずなのにここをfalseにした理由は何でしょう？

2023-01-20 06:49 UTC, yupimaru commented on frontend/app/src/components/Home.js
> +    console.log(data);
```js
console.log(data);
```

console.log()はデバッグツールですので、作業後は削除しましょう。

2023-01-20 06:49 UTC, yupimaru commented on frontend/app/src/components/auth/Registration.js
> +        console.log("registration res", response);
```js
console.log("registration res", response);
```

console.log()はデバッグツールですので、作業後は削除しましょう。

2023-01-20 06:49 UTC, yupimaru commented on frontend/app/src/App.js
> +        console.log(res);
```js
console.log(res);
```

console.log()はデバッグツールですので、作業後は削除しましょう。

2023-01-20 09:07 UTC, nishiodopeness commented
ログインの挙動動画を載せてもらえますか！？

2023-02-06 04:25 UTC, kenny-kento commented
@nishiodopeness 

下記挙動動画のご確認をお願いいたします！

https://user-images.githubusercontent.com/121996400/216883297-c78c73c0-7c0a-45fd-a574-a77c32dbc521.mov

2023-02-06 05:30 UTC, kenny-kento commented on backend/app/controllers/application_controller.rb
> +end
ご指摘ありがとうございます！
不要でしたので削除いたしました。

[c664ee0](https://github.com/kenny-kento/tips-memo/pull/2/commits/c664ee0490f651f3446a4e1055e326d554edb257)

2023-02-06 05:33 UTC, kenny-kento commented on backend/config/application.rb
> +    config.api_only = false
「config.api_only 」に関して改めて確認しました。
「= false」でもcookieが使用可能となりましたが懸念点があり下記修正しました。

◎修正
config.api_only = true
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore

◎懸念点
不要なミドルウェアまで読み込んでしまいapi専用と利用している前提から外れること。

◎該当コミット
[34eff90](https://github.com/kenny-kento/tips-memo/pull/2/commits/34eff905c1d49273e3c6b42ab76965cc42b37852)

2023-02-06 05:40 UTC, kenny-kento commented on frontend/app/src/components/Home.js
> +    console.log(data);
大変失礼いたしました！
削除いたしました。

[7e76d24](https://github.com/kenny-kento/tips-memo/pull/2/commits/7e76d243770e7237ef520f427a4ea08198c26b82)

2023-02-06 05:40 UTC, kenny-kento commented on frontend/app/src/components/auth/Registration.js
> +        console.log("registration res", response);
大変失礼いたしました！
削除いたしました。

[b25660a](https://github.com/kenny-kento/tips-memo/pull/2/commits/b25660a331e9bb751ab6c1046d244bf5281f3a60)

2023-02-06 05:40 UTC, kenny-kento commented on frontend/app/src/App.js
> +        console.log(res);
大変失礼いたしました！
削除いたしました。

[b25660a](https://github.com/kenny-kento/tips-memo/pull/2/commits/b25660a331e9bb751ab6c1046d244bf5281f3a60)

2023-02-07 00:31 UTC, nishiodopeness approved these changes

2023-02-07 00:31 UTC, nishiodopeness commented
LGTM~

2023-02-07 01:12 UTC, jun-yuaka approved these changes

2023-02-07 03:17 UTC, yupimaru approved these changes
2人がLGTM出してるからきっとLGTM

2023-02-07 04:11 UTC, merged